export const resources = [
  // ── CATÁLOGOS BASE ──────────────────────────────
  {
    key: 'tipos-variedad-arbol',
    title: 'Tipos de Variedad de Árbol',
    endpoint: '/tipos-variedad',
    idField: 'ID_TIPO_ARBOL',
    paramName: 'id_tipo_arbol',
    fields: [
      { name: 'nombre_arbol', label: 'Nombre del árbol', type: 'text', required: true },
      { name: 'tipo_uso', label: 'Tipo de uso', type: 'text' },
      { name: 'descripcion', label: 'Descripción', type: 'text' },
    ],
  },
  {
    key: 'tipos-fertilizante',
    title: 'Tipos de Fertilizante',
    endpoint: '/tipo-fertilizante',
    idField: 'ID_FERTILIZANTE',
    paramName: 'id_fertilizante',
    fields: [
      { name: 'nombre_fertilizante', label: 'Nombre', type: 'text', required: true },
      { name: 'tipo_fertilizante', label: 'Tipo', type: 'text' },
      { name: 'nutrientes_principales', label: 'Nutrientes principales', type: 'text' },
      { name: 'metodo_aplicacion', label: 'Método de aplicación', type: 'text' },
      { name: 'frecuencia', label: 'Frecuencia', type: 'text' },
      { name: 'descripcion', label: 'Descripción', type: 'text' },
    ],
  },
  {
    key: 'tipos-tratamiento',
    title: 'Tipos de Tratamiento',
    endpoint: '/tipo-tratamiento',
    idField: 'ID_TIPO_TRATAMIENTO',
    paramName: 'id_tipo_tratamiento',
    fields: [
      { name: 'nombre_tratamiento', label: 'Nombre', type: 'text', required: true },
      { name: 'categoria', label: 'Categoría', type: 'text' },
      { name: 'metodo_aplicacion', label: 'Método de aplicación', type: 'text' },
      { name: 'frecuencia', label: 'Frecuencia', type: 'text' },
      { name: 'descripcion', label: 'Descripción', type: 'text' },
    ],
  },
  {
    key: 'estados-arbol',
    title: 'Estados del Árbol',
    endpoint: '/estado-arbol',
    idField: 'ID_ESTADO',
    paramName: 'id_estado',
    fields: [
      { name: 'nombre_estado', label: 'Nombre del estado', type: 'text', required: true },
      { name: 'orden_ciclo', label: 'Orden del ciclo', type: 'number' },
      { name: 'es_productivo', label: 'Es productivo (S/N)', type: 'text' },
      { name: 'descripcion', label: 'Descripción', type: 'text' },
    ],
  },
  {
    key: 'plagas-enfermedades',
    title: 'Plagas y Enfermedades',
    endpoint: '/plaga-enfermedad',
    idField: 'ID_PLAGA',
    paramName: 'id_plaga',
    fields: [
      { name: 'nombre_plaga', label: 'Nombre', type: 'text', required: true },
      { name: 'tipo_plaga', label: 'Tipo', type: 'text' },
      { name: 'nivel_riesgo', label: 'Nivel de riesgo', type: 'text' },
      { name: 'descripcion', label: 'Descripción', type: 'text' },
    ],
  },
  {
    key: 'fincas',
    title: 'Fincas',
    endpoint: '/finca',
    idField: 'ID_FINCA',
    paramName: 'id_finca',
    fields: [
      { name: 'nombre_finca', label: 'Nombre de finca', type: 'text', required: true },
      { name: 'ubicacion', label: 'Ubicación', type: 'text' },
      { name: 'area_hectareas', label: 'Área (ha)', type: 'number' },
      { name: 'propietario', label: 'Propietario', type: 'text' },
      { name: 'telefono_contacto', label: 'Teléfono', type: 'text' },
      { name: 'descripcion', label: 'Descripción', type: 'text' },
    ],
  },
  // ── DEPENDEN DE CATÁLOGOS BASE ───────────────────
  {
    key: 'sectores',
    title: 'Sectores',
    endpoint: '/sector',
    idField: 'ID_SECTOR',
    paramName: 'id_sector',
    fields: [
      { name: 'id_finca', label: 'ID finca', type: 'number', required: true },
      { name: 'nombre_sector', label: 'Nombre del sector', type: 'text', required: true },
      { name: 'area_hectareas', label: 'Área (ha)', type: 'number' },
      { name: 'numero_surcos', label: 'Número de surcos', type: 'number' },
      { name: 'posiciones_por_surco', label: 'Posiciones por surco', type: 'number' },
      { name: 'tipo_cultivo', label: 'Tipo de cultivo', type: 'text' },
    ],
  },
  {
    key: 'arboles',
    title: 'Árboles',
    endpoint: '/arbol',
    idField: 'ID_ARBOL',
    paramName: 'id_arbol',
    fields: [
      { name: 'id_sector', label: 'ID sector', type: 'number', required: true },
      { name: 'id_tipo_variedad_arbol', label: 'ID tipo variedad', type: 'number', required: true },
      { name: 'id_estado', label: 'ID estado', type: 'number', required: true },
      { name: 'numero_surco', label: 'Número de surco', type: 'number' },
      { name: 'descripcion', label: 'Descripción', type: 'text' },
    ],
  },
  // ── REGISTROS (dependen de Árboles) ─────────────
  {
    key: 'historial-estados',
    title: 'Historial de Estados',
    endpoint: '/historial-estado',
    idField: 'ID_HISTORIAL',
    paramName: 'id_historial',
    fields: [
      { name: 'id_arbol', label: 'ID árbol', type: 'number', required: true },
      { name: 'id_estado_anterior', label: 'ID estado anterior', type: 'number' },
      { name: 'id_estado_nuevo', label: 'ID estado nuevo', type: 'number', required: true },
      { name: 'fecha_cambio', label: 'Fecha de cambio', type: 'date' },
      { name: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    key: 'registros-plaga',
    title: 'Registros de Plaga',
    endpoint: '/registro-plaga',
    idField: 'ID_REGISTRO',
    paramName: 'id_registro',
    fields: [
      { name: 'id_arbol', label: 'ID árbol', type: 'number', required: true },
      { name: 'id_plaga', label: 'ID plaga', type: 'number', required: true },
      { name: 'fecha_deteccion', label: 'Fecha de detección', type: 'date' },
      { name: 'fecha_resolucion', label: 'Fecha de resolución', type: 'date' },
      { name: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    key: 'registros-tratamiento',
    title: 'Registros de Tratamiento',
    endpoint: '/registro-tratamiento',
    idField: 'ID_REGISTRO',
    paramName: 'id_registro',
    fields: [
      { name: 'id_arbol', label: 'ID árbol', type: 'number', required: true },
      { name: 'id_tipo_tratamiento', label: 'ID tipo tratamiento', type: 'number', required: true },
      { name: 'id_fertilizante', label: 'ID fertilizante', type: 'number' },
      { name: 'fecha_aplicacion', label: 'Fecha de aplicación', type: 'date' },
      { name: 'observaciones', label: 'Observaciones', type: 'text' },
    ],
  },
  {
    key: 'resiembras',
    title: 'Resiembras',
    endpoint: '/resiembra',
    idField: 'ID_RESIEMBRA',
    paramName: 'id_resiembra',
    fields: [
      { name: 'id_arbol_nuevo', label: 'ID árbol nuevo', type: 'number', required: true },
      { name: 'fecha_resiembra', label: 'Fecha de resiembra', type: 'date' },
      { name: 'motivo', label: 'Motivo', type: 'text' },
    ],
  },
];